### ISSUE TITLE
node fetch not included in dependencies

### ISSUE THREAD

**Issue by joelazwar** [Supercraft888/lFinder#3]
A minor issue, the program didnt work the first time after i npm installed because it couldnt find the node fetch module.

I noticed you used it in your code and checked your package.json file and it was missing from the dependencies.

https://github.com/Supercraft888/lFinder/blob/59729eebfe30f8e4b73e7a537ec990d5d6ead113/package.json#L14-L18

**Comment by Supercraft888** [comment]
Thanks for the heds up!  Updated them
